### ISSUE TITLE
ViewModelにNavigateを付けると'KamishibaiTest2' は既に 'PresentationService' の定義を含んでいますとエラーが出る

### ISSUE THREAD

**Issue by kyamamoto03** [nuitsjp/KAMISHIBAI#14]
VS 2022 Version 17.3.2
で[GettingStart](https://zenn.dev/nuits_jp/books/introduction-to-kamishibai/viewer/02-getting-started)
を写経していたところ、ViewModelにNavigateを付けると
![image](https://user-images.githubusercontent.com/17057569/186598674-973d9b0c-cce7-4d4d-a501-1b16e982ae0d.png)
とエラーが出ます。
以前（おそらく２か月前程度）はここでエラーは出なかったように思うのですが。
お時間があるときに見ていただけると助かります。

**Comment by kyamamoto03** [comment]
もしかしたら、SourceGeneratorが２重起動する[バグ](https://github.com/CommunityToolkit/dotnet/issues/343)
が関係でしょうか？

**Comment by nuitsjp** [comment]
報告ありがとうございます！
ちょっと今日明日は見れないかと思いますが、近日中に確認します。

**Comment by nuitsjp** [comment]
確認しました。
確かにGeneratorが2重起動するバグで、そのリンク先にある、こちらの対応で回避することができました。

- https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402

私はDirectory.Build.propsをこちらのように修正しましたが、.csprojに同様に記載しても良いようです。

- https://github.com/nuitsjp/KAMISHIBAI/commit/f6fb2774e9e3bb5540641a2e46ee18cc5cfe3e71

この問題は、ライブラリー側で対応できず、当面はアプリ側で対応する必要があるようです。
そのため、上記のような対応を実施してみてください。

KAMISHIBAI側から対応できないこともないのですが、やるべきことではない（将来的に不要なコードになる＆アプリ側での回避策がある）ため、すいませんが、アプリ側で対応をお願いします。

**Comment by nuitsjp** [comment]
このIssueは一旦クローズしますが、何かあればレスポンスください。

報告いただき、ありがとうございました。

**Comment by kyamamoto03** [comment]
.csprojに記載することでビルド出来るようになりました。
しっかり下まで読めばよかった。
対応ありがとうございました。

**Comment by nuitsjp** [comment]
某所で教えていただいたのですが、6.0.9で対応されるようです。
- https://github.com/dotnet/wpf/pull/6800
