### ISSUE TITLE
Does the GoBackAsync is reinitializing the view models?

### ISSUE THREAD

**Issue by Iulian-Liviu** [nuitsjp/KAMISHIBAI#16]
I use events to command, like the on-loaded event of a user control, and I want to know if, when I go back from a view, the view from which I navigated is resetting its state or remaining the same.

Thanks.

**Comment by Iulian-Liviu** [comment]
Sorry, it just seems it was an UI design mistake. KEEP UP THE GOOD WORK. Thanks for this awesome library.

**Comment by nuitsjp** [comment]
Glad to hear you got it resolved. 
Thanks for using it. I am very happy to hear you say that. 
If you have any more questions, please feel free to ask.
