### ISSUE TITLE
自動生成されたコードに警告が発生する

### ISSUE THREAD

**Issue by Freeesia** [nuitsjp/KAMISHIBAI#17]
StyleCopや独自の警告ルールを使用していると、SourceGeneratorによって生成されたコードに警告が発生し修正することができません。

生成するコードの先頭に以下2行出力することで回避することができるので、対応いただけると幸いです。
```cs
#pragma warning disable CS1591 
// <auto-generated />
```

https://github.com/dotnet/roslyn/issues/54119

**Comment by nuitsjp** [comment]
ご指摘ありがとうございます！
週明けまでには対応したいと思います。
遅れたらごめんなさい。

**Comment by nuitsjp** [comment]
対応は完了。もう一つのコードと合わせてリリースしたらクローズします。

**Comment by nuitsjp** [comment]
リリースしました。確認お願いします！
- https://github.com/nuitsjp/KAMISHIBAI/releases/tag/Release-2.0.0

**Comment by Freeesia** [comment]
ありがとうございます！
無事警告が抑制されました。

**Comment by nuitsjp** [comment]
無事解決してよかったです。また何かあれば気軽にどうぞ！
