### ISSUE TITLE
自動生成されたダイアログを開く拡張メソッドでダイアログの結果を受け取れない

### ISSUE THREAD

**Issue by Freeesia** [nuitsjp/KAMISHIBAI#18]
`IPresentationServiceBase.OpenDialogAsync()`の戻り値は`Task<bool>`になっており、ダイアログの結果を受け取れますが、自動生成される`IPresentationService`および`PresentationService`の`Open~DialogAsync`では`Task`になっているため、ダイアログの結果を受け取れません。

基本的には拡張メソッドのほうが利用シーンは多いので、拡張メソッドでも結果を受け取れるようにしていただければと思います。

**Comment by nuitsjp** [comment]
ご指摘ありがとうございます！
う～ん、何か意図があってしたのか、そうじゃなかったのか、すぐ思い出せません。
今週平日は時間をとるのが困難なので、可能なら週末のうちに確認します。

場合によって、シグニチャ変更の発生する破壊的変更（つまり生成される方もTask<bool>に）するかもしれません。

**Comment by nuitsjp** [comment]
リリースしました。確認お願いします！
- https://github.com/nuitsjp/KAMISHIBAI/releases/tag/Release-2.0.0

**Comment by Freeesia** [comment]
こちらもご対応ありがとうございました。
キャストせず受け取れるようになり、捗ります！

**Comment by nuitsjp** [comment]
良かった！あっちでも書きましたが、今後も気軽にぜひどうぞ！
