### ISSUE TITLE
ダイアログが閉じられたときにViewModelが破棄されない

### ISSUE THREAD

**Issue by Freeesia** [nuitsjp/KAMISHIBAI#21]
`OpenDialogAsync`で開いたウィンドウは、ViewModelが`IDisposable`を継承していれば`CloseDialogAsync`を呼び出したタイミングで破棄されますが、`OpenDialogAsync`で開いたダイアログはViewModelが`IDisposable`を継承していても破棄されません。

ナビゲーションについても破棄されるようなので、ダイアログだけ破棄されないのは意図した挙動ではないかと思いますので、修正いただけるとありがたいです。

**Comment by nuitsjp** [comment]
ご報告ありがとうございます！

確かにその挙動は不具合ぽいですね。
まだ確認できていませんが、近いうちに対応いたします。

**Comment by nuitsjp** [comment]
遅くなりましたが、確認し修正したと思います。
正確には、OpenWindowAsyncまたはOpenDialogAsyncで開いたのちに、それぞれCloseした場合、リソースの破棄はつぎの3つが利用可能です。

1. IDisposedAware
2. IDisposingAsyncAware
3. IDispose

このうち、1番目のIDisposedAwareが機能しておらず、修正しました。
ご確認ください。

また応答がなかった場合でも、1週間をめどに本Issueはクローズさせていただきます。
よろしくお願いいたします。

**Comment by nuitsjp** [comment]
クラッカーいただいたということで、いったんクローズします。
ご協力ありがとうございました！

**Comment by Freeesia** [comment]
@nuitsjp 
申し訳ありません。自分の認識がズレていたので、コードを確認していて返答が遅くなりました。
結果として私の課題の内容に不備があり問題を適切にお伝えできていませんでした。

正しくは`CloseDialogAsync`や`CloseWindowAsync`で閉じたときは適切に破棄されるが、開いているWindow自身で閉じたとき(❌ ボタン、Escキー、DialogResultの設定)にVMのは破棄が呼ばれないということでした。

これらの処理をフックして明示的に`CloseDialogAsync`を呼ぶこともできますが、自動的に破棄してくれる方が理想かと思います。
`WindowService`側で`Window.Closed`のイベントをフックして破棄処理を呼ぶなどはいかがでしょうか？

もし、新しい課題を立てたほうが良ければご連絡ください。
