### ISSUE TITLE
NavigationFrame遷移を呼び出さずにWindowのClose[x]ボタン押下時に例外発生

### ISSUE THREAD

**Issue by jaizawa758** [nuitsjp/KAMISHIBAI#25]
バージョン：Kamishibai.Hosting 2.6.0

再現手順
https://zenn.dev/nuits_jp/books/introduction-to-kamishibai/viewer/02-getting-started
~~こちらのFirstPageに ```<kamishibai:NavigationFrame />``` 配置する~~
上記のページまで作成、F5 でデバッグ実行開始、Closeボタンをクリックする -> 例外発生
※ここでNavigateボタンクリック後にCloseボタンクリックならば例外は発生しない

![image](https://github.com/nuitsjp/KAMISHIBAI/assets/130111760/e1b76ec0-61a4-4caa-ae1d-95cc0cfb3d10)

**Comment by nuitsjp** [comment]
すいません、Issue完全に見落としていました。近いうちに対応実施します。

**Comment by nuitsjp** [comment]
すいません、遅くなりました。
[Release-3.0.1](https://github.com/nuitsjp/KAMISHIBAI/releases/tag/Release-3.0.1-for-WPF)で修正しました。
ご確認ください。

このIssueは確認いただけた場合、または一週間ほど経過でクローズします。

**Comment by jaizawa758** [comment]
期待通りに動作しています、ありがとうございます。
